### ISSUE TITLE
Wiki info still missing in popups

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#186]
![screen shot 2016-03-21 at 11 30 22 am](https://cloud.githubusercontent.com/assets/4074881/13923817/6e2cb7b0-ef58-11e5-80bc-c2fee3aed67d.png)

Seems to happen on all demos I've seen till now

**Comment by bandle** [comment]
The reason is that the wiki prohibits the usage in frames like this by setting HTTP Access Control Options:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

But we gave team F a possibility to fill the modals with their content by using some callbacks which are documented in our wiki.

**Comment by gyachdav** [comment]
is there an issue on F's we can refer here then?

**Comment by bandle** [comment]
I think the generic issue will do: https://github.com/Rostlab/JS16_ProjectF/issues/17

But for our projects page I'll load some placeholder data in there. Which explains how you can alter the modals content
